client/src/styles/GlobalStyles.tsx
client/src/styles/Layout.tsx

- 이슈 번호: #15
- Layout Component 생성 및 구현
- GlobalStyle RowFlex, ColFlex 추가 
Layout.tsx
```
import styled from 'styled-components';
/*최상위 컨테이너 */
export const ContainerWrap = styled.div`
display: flex;
justify-content: center;
margin: 40px 0;
`;
/* 컨텐츠 컨테이너 */
export const Container = styled.div`
width: 100%;
max-width: 90vw;
`;
/* 컨텐츠 컨테이너 + flex */
export const ContainerFlex = styled(Container)`
display: flex;
`;
/*컨텐츠 빈공간 채우게 */
export const Content = styled.div`
display: flex;
flex-grow: 1;
`;
/*모바일 좌우상하 공간*/
export const MobileContainerWrap = styled(Content)`
padding: 30px 40px;
`;
/*타블렛 좌우상하 공간*/
export const TabletContainerWrap = styled(Content)`
padding: 40px 80px;
`;
/*앱 좌우상하 공간*/
export const DesktopContainerWrap = styled(Content)`
padding: 60 95px;
`;
```
- 웹 컨테츠 가로 사이즈를 몇으로 정해야 …

[Style] Layout, GlobalStyle

---

client/package.json
client/src/components/common/Header/Header.styles.tsx
client/src/components/common/Header/Header.tsx
client/src/components/common/SearchBar/SearchBar.styles.tsx
client/src/components/common/SearchBar/SearchBar.tsx
client/src/styles/ResetCss.tsx
client/yarn.lock

- 이슈 번호: #32 #34 
- Header Component 구현
- SearchBar Component 구현
```js
Header.tsx
function Header() {
return (
<style.HeaderContainerWrap>
<style.HeaderContainerFlex>
<style.HeaderContent>
<style.LogoBox>
<style.Logo>
Pho<style.LogoPoint>to</style.LogoPoint>day
</style.Logo>
</style.LogoBox>
<SearchBar />
<style.LinkBox>
<style.HeaderLink to="/login">Login</style.HeaderLink>
<style.HeaderLink to="/signup">SignUp</style.HeaderLink>
</style.LinkBox>
</style.HeaderContent>
</style.HeaderContainerFlex>
</style.HeaderContainerWrap>
);
}
```
```js
SearchBar.tsx
function SearchBar() {
return (
<style.SearchBarWrap>
<BsSearch className="search-icon" />
<style.SearchBarInput></style.SearchBarInput>
</style.SearchBarWrap>
);
}
```
style 파일 `*` 전체 불러오고 `style 별칭` 사용하기
```
import * as style from …
```

[Design] Header, SearchBar 

---

client/package.json
client/src/components/common/Footer/Footer.styles.tsx
client/src/components/common/Footer/Footer.tsx
client/src/components/common/Header/Header.styles.tsx
client/src/components/common/Header/Header.tsx
client/src/components/common/SearchBar/SearchBar.styles.tsx
client/src/components/common/SearchBar/SearchBar.tsx
client/src/styles/ResetCss.tsx
client/yarn.lock

- 이슈 번호: #36
- Footer Component 구현
```js
function Footer() {
return (
<style.FooterContainerWrap>
<style.FooterContainerFlex>
<style.FooterContent>
<style.FooterSpan>
© 2023 GJS photoday Team. All rights reserved.
</style.FooterSpan>
</style.FooterContent>
</style.FooterContainerFlex>
</style.FooterContainerWrap>
);
}
```
헤더랑 딱 맞게 떨어지는 게 아닌 오른쪽 끝 쪽으로 붙여서 작업했습니다 ! 😉

[Design] Footer Component 구현

---

client/src/components/common/Header/Header.styles.tsx
client/src/components/common/Header/Header.tsx
client/src/components/common/SearchBar/SearchBar.styles.tsx
client/src/pages/Main/Main.styles.tsx
client/src/pages/Main/Main.tsx

- 이슈 번호: #32 #34 #40
- 메인 컨텐츠 디자인 작업
- 헤더 검색바 비활성화
- 검색바 사이즈 수정
```js
src/component/common/Header.jsx
function Header() {
return (
<style.HeaderContainerWrap>
<style.HeaderContainerFlex>
<style.HeaderContent>
<style.LogoBox>
<style.Logo>
Pho<style.LogoPoint>to</style.LogoPoint>day
</style.Logo>
</style.LogoBox>
{/* <SearchBar /> */}
<style.LinkBox>
<style.HeaderLink to="/login">Login</style.HeaderLink>
<style.HeaderLink to="/signup">SignUp</style.HeaderLink>
</style.LinkBox>
</style.HeaderContent>
</style.HeaderContainerFlex>
</style.HeaderContainerWrap>
);
}
```
```js
src/pages/Main.jsx
function Main() {
return (
<ContainerWrap>
<Container>
<style.MainContentBox>
<style.MainContent>
<style.SearchContentBox>
<SearchBar />
<style.SearchImgBox></style.SearchImgBox>
<style.MainTextBox> …
```

[Design] Main Content Component 구현

---

client/src/components/common/Button/Button.style.tsx
client/src/components/common/Button/Button.tsx
client/src/components/common/Header/Header.styles.tsx
client/src/components/common/Header/Header.tsx
client/src/components/common/SearchBar/SearchBar.styles.tsx
client/src/pages/Main/Main.styles.tsx
client/src/pages/Main/Main.tsx
client/src/styles/Variables.tsx

- 이슈 번호: #42 
- Button Component 구현
- Variables css 추가
```js
components/common/Button.tsx
interface ButtonProps {
variant: 'primary' | 'point';
shape: 'default' | 'round';
size: 'small' | 'medium' | 'large';
disabled?: boolean;
fullWidth?: boolean;
children: React.ReactNode;
}
function Button({
variant,
shape,
size,
disabled = false,
fullWidth = false,
children,
}: ButtonProps) {
return (
<style.ButtonBox
variant={variant}
shape={shape}
size={size}
fullWidth={fullWidth}
disabled={disabled}
>
{children}
</style.ButtonBox>
);
}
```
피그마에서 작업한  버튼 크기에 맞춰 작업했는데! 사이트 크기가 커져서 버튼이 작아 보이지 않을까 고민이네요..! 
```html
<Button
variant={'primary'}
shape={'round'}
size={'small'}
fullWidth={true}
disabled={false}
>
Upload Image
</Button>
```
사용 방법은 Button 컴포넌트를 가져와서 props 내려주시면 됩니다!  
fullWidth, disabled는 …

[Design] Button Component 구현

---

client/src/pages/AccountRecovery/AccountRecovery.tsx

- 이슈 번호: #21
- 비밀번호 찾기 클릭 시, 나오는 계정 복구 페이지 구현
- 기존에는 Login Page 하나를 두고 Outlet을 넣어 login, signup, account recovery를 outlet 위치에 컴포넌트 식으로 구현하여 넣었는데 페이지 단위로 하는 것이 좋을 것 같아 최종적으로 마무리 해서 올렸습니다.

[Design] Account Recovery Page 구현

---

client/src/components/common/Button/Button.style.tsx
client/src/components/common/Button/Button.tsx
client/src/components/common/Card/Card.style.tsx
client/src/components/common/Card/Card.tsx
client/src/components/common/Header/Header.styles.tsx
client/src/components/common/Header/Header.tsx
client/src/components/common/SearchBar/SearchBar.styles.tsx
client/src/components/common/SearchBar/SearchBar.tsx
client/src/pages/Main/Main.styles.tsx
client/src/pages/Main/Main.tsx

- 이슈 번호: #40 
-  Main Page  - SearchBar에 검색어 입력시 관련 사진이 출력 되고 기존에 있던 텍스트는 사라지도록 구현
```
src/pages/Main/Main.tsx
function Main() {
const [activeTextBox, setActiveTextBox] = useState(true);
....
<S_SearchContentBox>
<SearchBar setActiveTextBox={setActiveTextBox} />
<S_SearchImgBox textBoxActive={activeTextBox}>
<S_ContentImgBox>
<Card />
<Card />
<Card />
<Card />
<Card />
<Card />
<Card />
</S_ContentImgBox>
</S_SearchImgBox>
<S_MainTextBox textBoxActive={activeTextBox}>
<S_MainTextSpan>
free pics.
<br /> do anyhing (CC0). <br /> make magic
</S_MainTextSpan>
</S_MainTextBox>
</S_SearchContentBox>
...
}
```
```
src/pages/Main/Main.styles.tsx
export const S_SearchImgBox = styled.div`
margin-top: 20px;
width: 100%;
height: ${({ textBoxActive }: { textBoxActive: boolean }) =>
textBoxActive ? …
```

[Desgin] Main Page 구현

---

client/src/components/common/Header/Header.styles.tsx
client/src/components/common/Header/Header.tsx
client/src/components/common/Header/HeaderModal.styles.tsx
client/src/components/common/Header/HeaderModal.tsx

- 이슈 번호: #32 #83 
- 
- Header Modal Component 구현
-  Header Component 구현
```js
src/components/common/Header/HeaderModal.tsx
function HeaderModal() {
return (
<S_HeaderModalWrap>
<S_ModalNavBox>
<FaHouseUser className="mypage-icon" />
<S_ModalNavLink to="/mypage">MyPage</S_ModalNavLink>
</S_ModalNavBox>
<S_ModalNavBox>
<IoLogOut className="logout-icon" />
<S_ModalNavLink to="/logout">Logout</S_ModalNavLink>
</S_ModalNavBox>
</S_HeaderModalWrap>
);
}
```
- 로그인 여부에 따라 헤더가 다르고,  로그인 상태에서 아이콘을 클릭했을 때 위 사진과 같은 작은 모달이 나오게 됩니다. 
- push 하고 feat/mainContent 브랜치에서 작업한 걸 알게됐어요 😢 (feat/header 에서 작업했어야 하는데..)
다음부터 작업 전에 한 번 더 브랜치 확인하겠습니다.

[Feature] Header Modal Component, Header Component 구현

---

client/src/App.tsx
client/src/pages/Upload/Upload.styles.tsx
client/src/pages/Upload/Upload.tsx

⏪ [Design] Upload page 복구

---

client/src/App.tsx
client/src/pages/Search/Search.styled.tsx
client/src/pages/Search/Search.tsx

- 이슈 번호: #87 
- Search Page 구현
```
src/pages/Search.tsx
function Search() {
return (
<ContainerWrap>
<Container>
<S_SearchBox>
<S_SearchMenuBox>
<S_TagContentBox>
{/*임시 태그*/}
<S_Tag>나무</S_Tag>
<S_Tag>나무 무늬</S_Tag>
<S_Tag>나무 색</S_Tag>
</S_TagContentBox>
<S_SelectContentBox>
<SelectBox />
</S_SelectContentBox>
</S_SearchMenuBox>
<S_ImageCardBox>
<ImageCardList />
</S_ImageCardBox>
</S_SearchBox>
</Container>
</ContainerWrap>
);
}
```
```
App.tsx
{
path: '/tags',
element: <TagSearch />,
},
```
현재 해당 컴포넌트 폴더명과 파일명이 Search 로 되어 있는데 조금 더 직관적이게 TagSearch로 수정하겠습니다 :)

[Design] Search Page 구현

---

client/src/App.tsx
client/src/components/common/Header/Header.styles.tsx
client/src/components/common/Header/Header.tsx
client/src/components/common/Header/HeaderModal.styles.tsx
client/src/components/common/Header/HeaderModal.tsx
client/src/components/common/SelectBox/SelectBox.style.tsx
client/src/components/common/SelectBox/SelectBox.tsx
client/src/components/common/SelectBox/SelectBoxModal.style.tsx
client/src/components/common/SelectBox/SelectBoxModal.tsx
client/src/pages/Main/Main.styles.tsx
client/src/pages/Main/Main.tsx
client/src/pages/Search/Search.styled.tsx
client/src/pages/Search/Search.tsx
client/src/styles/Layout.tsx

- 이슈 번호: #32 #83 
- Header 레이아웃 수정 
- Header Modal css 수정 
기존 코드에서 스타일만 변경돼서 스크린샷과 변경로직은 생략합니다.

[Design] Header, Header Modal 레이아웃 및 css 수정 

---

client/src/App.tsx
client/src/components/common/SelectBox/SelectBox.style.tsx
client/src/components/common/SelectBox/SelectBox.tsx
client/src/components/common/SelectBox/SelectBoxModal.style.tsx
client/src/components/common/SelectBox/SelectBoxModal.tsx
client/src/pages/Main/Main.styles.tsx
client/src/pages/Main/Main.tsx
client/src/pages/Search/Search.styled.tsx
client/src/pages/Search/Search.tsx
client/src/styles/Layout.tsx

- 이슈 번호: #96  
- SelectBox Component 구현
- SelectBox Modal Component 구현
```js
src/component/common/SelectBox/SelectBox.tsx
function SelectBox() {
const [isActiveSelect, setIsActiveSelect] = useState(false);
const [isSelect, setIsSelect] = useState('최신순');
return (
<S_SelectBoxWrap onClick={() => setIsActiveSelect(!isActiveSelect)}>
<S_SelectSpan>{isSelect}</S_SelectSpan>
{isActiveSelect ? (
<BiChevronDown className="selectbox-icons" />
) : (
<BiChevronUp className="selectbox-icons" />
)}
{isActiveSelect && (
<SelectBoxModal isSelect={isSelect} setIsSelect={setIsSelect} />
)}
</S_SelectBoxWrap>
);
}
```
```js
src/component/common/SelectBox/SelectBoxModal.tsx
interface SelectBoxProps {
isSelect: string;
setIsSelect: (isSelect: string) => void;
}
function SelectBoxModal({ isSelect, …
```

[Design] SelectBox Component 구현

---

client/src/App.tsx
client/src/pages/ErrorPage/ErrorPage.style.tsx
client/src/pages/ErrorPage/ErrorPage.tsx

- 이슈 번호: #109 
- 404 Not Found Page 구현
```js
src/App.tsx
...
{
path: '/*',
element: <ErrorPage />,
},
```
```js
src/pages/ErroPage/ErroPage.tsx
function ErrorPage() {
return (
<S_ErrorPageWrap>
<S_ErrorPageContainer>
<S_ErrorBox>
<S_TextContainer>
<S_ErrorTitleH1>404</S_ErrorTitleH1>
<S_ErrorSubTitleBold>Page Not Found</S_ErrorSubTitleBold>
<S_ErrorSubTitleP>
The page you're looking for does not seem to exist
</S_ErrorSubTitleP>
</S_TextContainer>
<S_ButtonContainer>
<LinkButton variant="point" shape="default" size="large" url="/">
Go to Home
</LinkButton>
</S_ButtonContainer>
</S_ErrorBox>
</S_ErrorPageContainer>
</S_ErrorPageWrap>
);
}
```
사용자가 사이트에서 존재하지 않는 URL을 입력했을 때 보여지는 Not Found Page 구현했습니다.

[Design] 404 Not Found Page 구현

---

client/src/App.tsx
client/src/components/common/Button/Button.style.tsx
client/src/components/common/Button/Button.tsx
client/src/components/common/Button/LinkButton.tsx
client/src/components/common/Footer/Footer.styles.tsx
client/src/components/common/Footer/Footer.tsx
client/src/pages/ErrorPage/ErrorPage.style.tsx
client/src/pages/ErrorPage/ErrorPage.tsx

- 이슈 번호: #36
- Footer 팀명 변경 
```js
src/components/common/Footer/Footer.tsx
function Footer() {
return (
<S_FooterContainerWrap>
<S_FooterContainer>
<S_FooterSpan>
© 2023 MNK-photoday Team. All rights reserved.
</S_FooterSpan>
</S_FooterContainer>
</S_FooterContainerWrap>
);
}
```
변경된 팀 명으로 Footer 수정했습니다.

[Design] Footer 팀명 변경 

---

client/src/pages/Main/Main.styles.tsx
client/src/styles/ResetCss.tsx

- 이슈 번호: #121 
- Scrollbar Custom 작업
```js
src/components/Main/Main.styles.tsx
export const S_SearchImgBox = styled.div`
width: 100%;
height: ${({ textBoxActive }: { textBoxActive: boolean }) =>
textBoxActive ? '0%' : '400px'};
visibility: ${({ textBoxActive }: { textBoxActive: boolean }) =>
textBoxActive ? 'hidden' : 'visible'};
transition: 1s;
overflow-y: scroll;
margin: 10px 0;
&::-webkit-scrollbar {
width: 5px;
}
&::-webkit-scrollbar-thumb {
border-radius: 3px;
background: var(--color-primary-gray20);
}
`;
```
```js
src\styles\ResetCss.tsx
body {
&::-webkit-scrollbar {
width: 8px;
}
&::-webkit-scrollbar-thumb {
border-radius: 3px;
background: var(--color-primary-gray30);
}
}
```
Scrollbar Custom 작업 후 body 와 mainContent에 적용했습니다.

[Design] Scrollbar Custom 작업

---

client/src/components/common/ImageCard/ImageCard.style.tsx
client/src/components/common/ImageCard/ImageCard.tsx

- 이슈 번호: #50
- ImageCard hover 작업
```js
src/components/ImageCard/ImageCard.tsx
function ImageCard() {
return (
<S_CardImagePicture>
<S_CardImageLink to="/detail/1">
<S_CardImage src={CardImage} alt="검색된 이미지" />
</S_CardImageLink>
<S_OverlayControls>
<S_OverlayControlsBox>
<S_IconBox>
<FaHeart size={20} className="like-icon" />
</S_IconBox>
<S_IconBox>
<FaBookmark size={18} className="bookmark-icon" />
</S_IconBox>
</S_OverlayControlsBox>
</S_OverlayControls>
</S_CardImagePicture>
);
}
```
```js
src/components/ImageCard/ImageCard.styles.tsx
export const S_OverlayControls = styled.div`
width: 100%;
position: absolute;
padding: 5px 20px;
bottom: 0;
box-sizing: border-box;
opacity: 0;
transition: 1s;
background: linear-gradient(
180deg,
rgba(25, 27, 38, 0),
rgba(25, 27, 38, 0.56)
); …
```

[Design] ImageCard hover 작업

---

client/src/components/Login/Input/Input.tsx
client/src/components/Login/LoginValidationLogic/LoginValidationLogic.tsx
client/src/components/User/UserFollwModal/ModalListItem.styles.tsx
client/src/components/User/UserFollwModal/ModalListItem.tsx
client/src/components/User/UserFollwModal/UserFollwModal.styles.tsx
client/src/components/User/UserFollwModal/UserFollwModal.tsx
client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
client/src/components/User/UserInfoArea/UserInfoArea.tsx
client/src/components/User/UserPageSubTitle/UserPageSubTitle.tsx
client/src/components/User/UserThumnailArea/UserThumnailArea.styles.tsx
client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
client/src/pages/AccountRecovery/AccountRecovery.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Signup/Signup.tsx
client/src/pages/User/User.tsx

- 이슈 번호: #86 
- 이슈 번호: #124
- Follow(팔로잉, 팔로워) 클릭 시 나오는 Modal 구현
- 피그마 상에서 결정했던 위치가 생각보다 예쁘지가 않아서 위치는 고민 중에 있습니다.
- 모달에서 보이는 드래그바 부분은 추후에 수정하도록 하겠습니다.

[Design] Follow Modal 구현

---

client/src/components/common/Skeleton/MainSkeleton.tsx
client/src/components/common/Skeleton/Skeleton.style.tsx
client/src/components/common/Skeleton/Skeleton.tsx
client/src/pages/Main/Main.styles.tsx
client/src/pages/Main/Main.tsx

- 이슈 번호: #13 
-  Main Skeleton 적용
```js
src/components/common/MainSkeleton.tsx
function MainSkeleton({ count }: { count: number }) {
return (
<>
{Array.from({ length: count }).map((_, index) => (
<S_MainImgBox key={index}>
<Skeleton width={700} height={400} animation={true} />
</S_MainImgBox>
))}
</>
);
}
```
```js
src/components/common/Skeleton.tsx
function MainSkeleton({ count }: { count: number }) {
return (
<>
{Array.from({ length: count }).map((_, index) => (
<S_MainImgBox key={index}>
<Skeleton width={700} height={400} animation={true} />
</S_MainImgBox>
))}
</>
);
}
```
```js
export type SkeletonProps = {
width?: number; //가로 사이즈
height?: number; //세로 사이즈
circle?: boolean; //원형 스켈레톤
rounded?: boolean; //모서리 둥글게
unit?: string; //px or % 단위 선택
animation?: boolean; //애니메이션 유무
color?: …
```

[Design] Main Skeleton 적용

---

client/src/pages/Main/Main.styles.tsx
client/src/pages/Main/Main.tsx

- 이슈 번호: #13 
- Main 반응형 css 작업
```js
src/pages/Main/Main.tsx
function Main() {
const [activeTextBox, setActiveTextBox] = useState(true);
/*로딩상태 전역으로 관리할까 고민 중입니당*/
const [loading, setLoading] = useState<boolean>(true);
/*임시로 로딩상태 만든 코드*/
setTimeout(() => setLoading(false), 1000);
});
return (
<ContainerWrap>
<Container>
<S_MainContentBox>
<S_SearchContentBox>
<SearchBar setActiveTextBox={setActiveTextBox} />
<S_SearchImgBox textBoxActive={activeTextBox}>
<S_ContentImgBox>
<ImageCard />
<ImageCard />
<ImageCard />
<ImageCard />
<ImageCard />
<ImageCard />
<ImageCard />
</S_ContentImgBox>
</S_SearchImgBox>
<S_MainTextBox textBoxActive={activeTextBox}>
<S_MainTitle>
free pics.
<br /> do anyhing (CC0). <br /> make magic
</S_MainTitle>
</S_MainTextBox>
</S_SearchContentBox> …
```

[Design]  Main 반응형 css 작업

---

server/Dockerfile
server/docker-compose.yml
server/src/test/resources/application.yml

- 이슈 번호: #161 
- 테스트 코드 DB 설정
- 테스트 yml , Dockerfile, docker-compose 수정

[Docs] 테스트 코드 DB 설정 #161

---

server/src/main/java/com/photoday/photoday/excpetion/ExceptionControllerAdvice.java
server/src/main/java/com/photoday/photoday/mail/config/EmailConfiguration.java
server/src/main/java/com/photoday/photoday/mail/config/EmailSendable.java
server/src/main/java/com/photoday/photoday/mail/config/EmailSender.java
server/src/main/java/com/photoday/photoday/mail/config/SimpleEmailSendable.java
server/src/main/java/com/photoday/photoday/mail/developer/DeveloperApplicationEvent.java
server/src/main/java/com/photoday/photoday/mail/developer/DeveloperEventListener.java
server/src/main/java/com/photoday/photoday/mail/user/UserApplicationEvent.java
server/src/main/java/com/photoday/photoday/mail/user/UserEventListener.java
server/src/main/java/com/photoday/photoday/security/service/AuthUserServiceImpl.java
server/src/main/java/com/photoday/photoday/util/TempPassword.java

- 이슈 번호: #103 
exception 발생 시 개발자에게 이메일 발송하는 로직 추가
임시 비밀번호 발급 로직 수정 
임시 비밀번호 발급 로직 리팩토링 (현보님이 도와주심)

[Feat, Fix] Feat/mail 

---

client/src/api/Login.ts
client/src/pages/Login/Login.tsx
client/src/store/authSlice.ts

- 이슈 번호: #145
- userSlice에 userId 추가

[Feature] Redux userSlice 상태 추가

---

server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java
server/src/test/resources/application.yml

- 이슈 번호: #135 
checkFollow 반영 안 되는 부분 수정
userMapper에서 checkFollow 로직을 수정함

[Bug] checkFollow 버그 수정 

---

server/src/test/java/com/photoday/photoday/helper/snippets/RestDocsSnippets.java
server/src/test/java/com/photoday/photoday/tag/controller/TagControllerTest.java
server/src/test/java/com/photoday/photoday/user/mapper/UserMapperTest.java

searchByTags, userToUserResponse: 테스트 실패하는 로직 리팩토링

Feat/test searchByTags, userToUserResponse: 테스트 실패하는 로직 리팩토링

---

client/src/App.tsx
client/src/api/Search.ts
client/src/components/common/ImageCard/ImageCard.styles.tsx
client/src/components/common/ImageCard/ImageCard.tsx
client/src/components/common/ImageCardList/ImageCardList.styles.tsx
client/src/components/common/ImageCardList/ImageCardList.tsx
client/src/components/common/SearchBar/SearchBar.tsx
client/src/components/common/Skeleton/ImageCardSkeleton.tsx
client/src/context/ItemContext.tsx
client/src/context/LoadintContext.tsx
client/src/context/PageNumContext.tsx
client/src/context/SearchContext.tsx
client/src/pages/Main/Main.tsx
client/src/pages/Search/Search.styles.tsx
client/src/pages/Search/Search.tsx

- 이슈 번호: #173 #172 #163
- 무한 스크롤 
- contextAPI 적용 
- 태그 검색 기능 구현
```js
src/components/common/ImageCardList.tsx
export type ImageCardListProps = {
width: number;
height?: number;
matrix?: 'columns' | 'rows';
};
export type ImageItemProps = {
imageId: number;
mageUrl: string;
like: boolean;
bookmark: false;
};
function ImageCardList({
width,
height,
matrix = 'columns',
}: ImageCardListProps) {
const [hasMore, setHasMore] = useState<boolean>(true);
const observer = useRef<IntersectionObserver>();
const endRef = useRef<HTMLDivElement>(null);
const ITEM_CONTEXT = useContext(ItemContext);
const LOADING_CONTEXT = useContext(LoadingContext);
const SEARCH_CONTEXT = useContext(SearchContext);
const PAGE_NUM_CONTEXT = useContext(PageNumContext);
if …
```

[Feature] 무한스크롤 및 태그 검색 기능 구현

---

server/src/main/java/com/photoday/photoday/follow/controller/FollowController.java
server/src/main/java/com/photoday/photoday/follow/dto/FollowDto.java
server/src/main/java/com/photoday/photoday/follow/mapper/FollowMapper.java
server/src/main/java/com/photoday/photoday/follow/service/FollowService.java
server/src/main/java/com/photoday/photoday/follow/service/FollowServiceImpl.java
server/src/test/java/com/photoday/photoday/follow/controller/FollowControllerTest.java
server/src/test/java/com/photoday/photoday/follow/mapper/FollowMapperTest.java
server/src/test/java/com/photoday/photoday/follow/service/FollowServiceImplTest.java
server/src/test/java/com/photoday/photoday/helper/snippets/RestDocsSnippets.java

- 이슈 번호: #191 
checkFollow 버그 수정.
follow 조회 시 response 수정.
FollowMapper 에서 checkFollow 로직 수정 및 불필요 메서드 삭제. 
불필요 주석 삭제.
엔드포인트 추가. 
서비스 로직 수정. 
follow 테스트는 수정 중

[Bug] checkFollow 버그 수정

---

server/src/main/java/com/photoday/photoday/user/controller/UserController.java
server/src/main/java/com/photoday/photoday/user/service/UserService.java
server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java

- 이슈 번호: #193 
유저 이미지 삭제 기능 기본 이미지로 변경

[Feat] 유저 이미지 삭제 기능 기본 이미지로 변경 #193

---

server/src/main/java/com/photoday/photoday/user/controller/UserController.java
server/src/main/java/com/photoday/photoday/user/dto/UserDto.java
server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java
server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java

- 이슈 번호: #197 
마이페이지 본인 확인 기능 추가

[Fix] 마이페이지 본인 확인 기능 추가

---

client/src/components/common/ImageCard/MainImageCard.styles.tsx
client/src/components/common/ImageCard/MainImageCard.tsx
client/src/components/common/Skeleton/MainSkeleton.tsx
client/src/pages/Main/Main.styles.tsx
client/src/pages/Main/Main.tsx

- 이슈 번호: #199
- Main Page 인기있는 이미지 랜덤 출력 
```js
src/components/common/ImageCard/MainImageCard.tsx
function MainImageCard() {
/*데이터 호출 전에 테스트 코드입니다. */
const Mainimages: string[] = [img5, img6, img7, img8, img9, img10, img11];
const [isloading, setIsLoading] = useState(true);
const [mainImg, serMainImg] = useState({
url1: '',
url2: '',
});
const randomNum1 = Math.floor(Math.random() * Mainimages.length);
const randomNum2 = Math.floor(Math.random() * Mainimages.length);
setIsLoading(true);
serMainImg({
url1: Mainimages[randomNum1],
url2: Mainimages[randomNum2],
});
setIsLoading(false);
}, []);
return (
<S_MainImageContentBox>
{isloading ? (
<MainSkeleton count={2} height={420} />
) : (
<S_MainImageContentWrap>
<S_MainImgBox to="/">
<S_MainImg src={mainImg.url1} alt="인기있는 …
```

[Feature] Main Page 인기있는 이미지 랜덤 출력 구현

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
server/src/main/java/com/photoday/photoday/security/dto/LoginDto.java
server/src/test/java/com/photoday/photoday/follow/mapper/FollowMapperTest.java
server/src/test/java/com/photoday/photoday/follow/service/FollowServiceImplTest.java
server/src/test/java/com/photoday/photoday/helper/security/SecurityTestHelper.java
server/src/test/java/com/photoday/photoday/helper/snippets/RestDocsSnippets.java
server/src/test/java/com/photoday/photoday/image/mapper/ImageMapperTest.java
server/src/test/java/com/photoday/photoday/security/controller/AuthControllerTest.java
server/src/test/java/com/photoday/photoday/security/controller/LoginTest.java
server/src/test/java/com/photoday/photoday/user/mapper/UserMapperTest.java

- 이슈 번호: #201, #203
로그인 테스트 작성, 테스트 리팩토링
springsecurity가 webmvctest에서 로딩이 안돼요

Feat/test 로그인 테스트, 리팩토링

---

server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java

- 이슈 번호: #207 
OAuth2 토큰 기능 수정, 인가 설정

[Fix] OAuth2 토큰 기능 수정, 인가 설정

---

client/src/components/common/ImageCard/ImageCard.styles.tsx
client/src/components/common/ImageCard/ImageCard.tsx
client/src/components/common/ImageCard/ImageData.tsx
client/src/components/common/ImageCard/MainImageCard.styles.tsx
client/src/components/common/ImageCard/MainImageCard.tsx
client/src/components/common/ImageCardList/ImageCardList.styles.tsx
client/src/components/common/ImageCardList/ImageCardList.tsx
client/src/pages/Main/Main.styles.tsx

- 이슈 번호: #199
- Main Page  이미지 랜덤 출력 테스트 코드 수정
- 그 외 Main styles 변경
```js
export const Mainimages = [
{
imageId: 50,
imageUrl:
'https://gjs-photoday-practice.s3.ap-northeast-2.amazonaws.com/20221115_204213.jpg',
like: false,
bookmark: false,
},
{
imageId: 51,
imageUrl:
'https://gjs-photoday-practice.s3.ap-northeast-2.amazonaws.com/20221124_133029.jpg',
like: false,
bookmark: false,
},
{
imageId: 52,
imageUrl:
'https://gjs-photoday-practice.s3.ap-northeast-2.amazonaws.com/20221022_181455.jpg',
like: false,
bookmark: false,
},
];
```
```js
function MainImageCard() {
/*데이터 호출 전에 테스트 코드입니다. */
const [items, setItems] = useState<ImageItemProps[]>([]);
const [isloading, setIsLoading] = useState(true);
const randomNum1 = Math.floor(Math.random() * 3);
const randomNum2 = …
```

[Feature]  Main Page  이미지 랜덤 출력 테스트 코드 수정

---

client/src/api/User.ts
client/src/components/User/UserContentSection/UserContentSection.styles.tsx
client/src/components/User/UserContentSection/UserContentSection.tsx
client/src/components/User/UserFollwModal/ModalListItem.styles.tsx
client/src/components/User/UserFollwModal/ModalListItem.tsx
client/src/components/User/UserFollwModal/UserFollwModal.styles.tsx
client/src/components/User/UserFollwModal/UserFollwModal.tsx
client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
client/src/components/User/UserInfoArea/UserInfoArea.tsx
client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
client/src/pages/User/User.tsx
client/src/store/userSlice.ts

- 이슈 번호: #169 
- 이슈 번호: #210
- Follow 기능 구현
> 해당 User 팔로우 여부 표시, 클릭 => 팔로우 / 언팔
팔로워 | 팔로잉 부분 각 클릭 시, 팔로워 | 팔로잉 모달 노출
모달에서 팔로워 | 팔로잉 하는 유저 프로필 | 유저 닉네임 | 팔로우 여부
모달에서 팔로우 여부 클릭 시 => 팔로우 / 얼팔
팔로우 / 언팔 시, 실시간으로 팔로워 | 팔로잉 숫자 변경
팔로워 / 팔로잉 유저 클릭 시, 해당 유저 페이지로 이동
```tsx
const fetchData = async () => {
try {
const response = await getFollows(myPage ? id : userId);
if (tap === 'follower') {
setFollowList(response.data.userFollower);
} else {
setFollowList(response.data.userFollowing);
}
} catch (error) {
alert(error);
}
};
fetchData();
}, [tap, followerCount, followingCount]);
```
```tsx
const deleteProfileHandler = async () => {
try {
const response = await deleteProfile();
dispatch(setData(response));
} catch (error) {
alert(error);
}
};
```
- 본인이면 Follow 아이콘 안 보임
- 아무도 없을 때
- …

[Feature] Follow 기능, 프로필 이미지 삭제 기능 구현 

---

client/src/api/Login.ts
client/src/components/Login/GoogleButton/GoogleButton.styles.tsx
client/src/components/Login/GoogleButton/GoogleButton.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Main/Main.tsx
client/src/pages/User/User.tsx
client/src/store/authSlice.ts
client/src/store/store.ts

- 이슈 번호: #145
- 소셜 로그인 구현
```tsx
export const socialLogin = () => {
const urlParams = new URLSearchParams(window.location.search);
const userId: any = urlParams.get('userId');
const userProfileImage: string | null = urlParams.get('userProfileImage');
const authorization: any = `Bearer ${urlParams.get('accessToken')}`;
localStorage.setItem('accessToken', authorization);
localStorage.setItem('id', userId);
return { userId, userProfileImage };
};
```
```
if (window.location.href.includes('userId')) {
const { userId, userProfileImage } = socialLogin();
dispatch(login({ userId, userProfileImage }));
const url = window.location.href.split('?')[0];
window.history.replaceState({}, document.title, url);
}
}, [navigate]);
```

[Feature] 소셜 로그인 기능 구현

---

client/src/api/Image.ts
client/src/api/Search.ts
client/src/components/common/Header/Header.tsx
client/src/components/common/Header/HeaderModal.tsx
client/src/components/common/ImageCard/ImageCard.styles.tsx
client/src/components/common/ImageCard/ImageCard.tsx
client/src/components/common/ImageCardList/ImageCardList.tsx

- 이슈 번호: #212 
- 좋아요 기능 구현
- 북마크 기능 구현
- 로그인 여부에 따라 헤더 변경
```js
src/components/common/ImageCard.tsx
type ImageCardProps = {
item: {
imageId: number;
imageUrl: string;
};
};
type ImageDetail = {
like: boolean;
bookmark: boolean;
};
function ImageCard({ item }: ImageCardProps) {
const { pathname } = useLocation();
const [detail, setDetail] = useState<ImageDetail>({
like: false,
bookmark: false,
});
const [likestate, setlikeState] = useState<boolean>(false);
const [bookstate, setBookmarkState] = useState<boolean>(false);
const clickEventHanelr = async (type: string) => {
if (type === 'like') {
await patchLikeImage(item.imageId);
setlikeState(detail.like);
} else if (type === 'bookmark') {
await patchBookmarkImage(item.imageId);
setBookmarkState(detail.bookmark);
}
}; …
```

[Feature]  좋아요, 북마크 기능 구현 

---

server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java

- 이슈 번호: #215 
User기능 checkAdmin 메서드 오류 수정

[Fix] User기능 checkAdmin 메서드 오류 수정 #215

---

client/src/components/User/UserThumnailArea/UserThumnailArea.tsx

- 이슈 번호: #169
- 이미지 변경 시, userProfileImage 값 변경
```tsx
try {
const response = await updateFile(file.file);
dispatch(setData(response));
const { profileImageUrl } = response.data;
localStorage.setItem('userProfileImage', profileImageUrl);
} 
```

[Feature] 이미지 변경 시, userProfileImage 값 변경

---

client/src/components/Login/Input/Input.styles.tsx
client/src/components/Login/LoginSection/LoginSection.styles.tsx
client/src/components/Signup/TermsGuideModal/TermsGuideModal.styles.tsx
client/src/pages/Login/Login.styles.tsx

- 이슈 번호: #145
- Login, Signup, AccountRecovery page 반응형 css 작업
```tsx
export const S_ContentSection = styled.section`
display: flex;
justify-content: center;
width: 450px;
position: fixed;
right: 0;
background: var(--white);
transition: background-color 0.5s ease-in-out;
@media screen and (max-width: 1024px) and (min-width: 415px) {
background: #ffffffb0;
transition: background-color 0.5s ease-in-out;
}
@media screen and (max-width: 414px) {
width: 100%;
background: #ffffffb0;
}
`;
```

[Design] Login page 반응형 css 추가

---

server/src/main/java/com/photoday/photoday/security/filter/JwtAuthenticationFilter.java
server/src/main/java/com/photoday/photoday/security/filter/JwtVerificationFilter.java
server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java

- 이슈 번호: #
user status 문자 불일치 해결

Hotfix/compile 긴급 컴파일 오류 해결 

---

client/src/components/Login/Input/Input.styles.tsx
client/src/components/Login/LoginSection/LoginSection.styles.tsx
client/src/components/User/UserContentSection/UserContentSection.styles.tsx
client/src/components/User/UserContentSection/UserContentSection.tsx
client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
client/src/components/User/UserInfoArea/UserInfoArea.tsx
client/src/components/User/UserThumnailArea/UserThumnailArea.styles.tsx
client/src/pages/User/User.styles.tsx

- 이슈 번호: #145
- User page 반응형 css 추가

[Design] User page 반응형 css 추가

---

server/src/main/java/com/photoday/photoday/image/dto/ImageDto.java
server/src/main/java/com/photoday/photoday/image/mapper/ImageMapper.java

- 이슈 번호: #73 
image response에 myImage, checkAdmin 필드 추가하였습니다.

[Feature] image response에 myImage, checkAdmin 필드 추가 #73

---

server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java

:hammer: [Fix] 인가 수정, 프론트 Origin 추가

---

server/Prometheus.yml

- 이슈 번호: #156 
Prometheus.yml target host 주소 변경

[Fix] Feat/log Prometheus.yml target host 주소 변경

---

server/Prometheus.yml
server/src/main/java/com/photoday/photoday/image/service/impl/ImageServiceImpl.java
server/src/main/java/com/photoday/photoday/mail/image/ImageDeleteEvent.java
server/src/main/java/com/photoday/photoday/mail/image/ImageEventListener.java

- 이슈 번호: #103
관리자에 의한 이미지 삭제시 or 신고 횟수 초과로 이미지 삭제시 
회원에게 이메일이 발송되도록 로직을 추가하였습니다.

[Feature] 관리자에 의해 or 신고 횟수 초과로 이미지 삭제시 회원에게 메일 발송 기능 추가

---

server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java

- 이슈 번호: #120 
관리자의 유저 삭제 기능
관리자가 회원 삭제 요청시 삭제가 아닌 ban처리 하는 것으로 로직 수정.
ban 기간은 1주일로 잡아뒀습니다.

[Fix] feat/user 관리자가 회원 삭제 요청시 ban처리로 로직 수정

---

server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
server/src/main/java/com/photoday/photoday/security/filter/JwtVerificationFilter.java
server/src/main/java/com/photoday/photoday/security/handler/UserAuthenticationEntryPoint.java
server/src/main/java/com/photoday/photoday/security/jwt/JwtProvider.java
server/src/main/java/com/photoday/photoday/security/utils/CookieUtil.java

- 이슈 번호: #
프론트 Origin 추가, 쿠키 도메인 수정

[Fix] 프론트 Origin 추가, 쿠키 도메인 수정

---

client/src/components/common/Header/Header.styles.tsx
client/src/components/common/Header/Header.tsx
client/src/components/common/ImageCard/MainImageCard.styles.tsx
client/src/components/common/ImageCardList/ImageCardList.styles.tsx
client/src/components/common/SearchBar/SearchBar.styles.tsx
client/src/components/common/SelectBox/SelectBox.style.tsx
client/src/pages/Main/Main.styles.tsx
client/src/pages/Search/Search.styles.tsx
client/src/styles/Layout.tsx

[Design] 헤더 반응형 구현 

---

client/src/pages/Detail/Detail.tsx

- 이슈 번호: #153
다운로드 버튼 이벤트 핸들러 수정
```js
const downloadFile = (): void => {
if (detailInfo) {
axios
.get<Blob>(detailInfo?.image, {
responseType: 'blob',
withCredentials: true,
})
.then((response) => {
const blob = new Blob([response.data]);
const a = document.createElement('a');
const url = window.URL.createObjectURL(blob);
a.href = url;
a.download = `download.jpg`;
console.log(a);
a.click();
window.URL.revokeObjectURL(url);
})
.catch((err) => {
console.log(err);
});
}
};
```

🔨 [Update] 다운로드 이벤트핸들러 수정 #153

---

server/docker-compose.yml
server/src/main/java/com/photoday/photoday/image/dto/ImageDto.java
server/src/main/java/com/photoday/photoday/user/dto/UserDto.java
server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java
server/src/main/resources/application.yml

- 이슈 번호: #85
User response reportCount 매핑 사항 수정했습니다. 
처음에 필드 이름을 reportedCount로 했어야 덜 헷갈렸을 듯.
알려주신 은수님 감사합니다.

[Fix] User Response ReportCount 값 매핑 수정

---

server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java

- 이슈 번호: #85 
user likeCount 버그 수정
유저가 좋아요 받은 숫자가 아니라, 좋아요 한 숫자가 반환된다는 것을 멘토링 시간에 테스트하다가 확인하고, 
유저가 좋아요 받은 숫자를 정상적으로 리턴하도록 버그를 수정했습니다!

[Hotfix] user likeCount 버그 수정

---

server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
server/src/main/java/com/photoday/photoday/security/controller/AuthController.java

- 이슈 번호: #235 
액세스 토큰 만료 확인 API 추가

[Feat] accessToken 만료 확인 API 추가

---

server/src/main/java/com/photoday/photoday/follow/service/impl/FollowServiceImpl.java
server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
server/src/main/java/com/photoday/photoday/security/controller/AuthController.java

- 이슈 번호: #236 
비회원이 팔로우 목록 조회시 나타나는 에러를 수정했습니다.

[Fix] Feat/follow 비회원이 follow 목록 조회시 나타나는 버그 수정

---

server/src/main/java/com/photoday/photoday/image/controller/ImageController.java
server/src/main/java/com/photoday/photoday/image/service/S3Service.java
server/src/main/java/com/photoday/photoday/image/service/impl/S3ServiceImpl.java
server/src/main/java/com/photoday/photoday/image/util/ImageUtils.java

[Feat] 이미지 다운 기능 추가

---

server/src/main/java/com/photoday/photoday/image/controller/ImageController.java
server/src/main/java/com/photoday/photoday/image/service/S3Service.java
server/src/main/java/com/photoday/photoday/image/service/impl/S3ServiceImpl.java
server/src/main/java/com/photoday/photoday/image/util/ImageUtils.java
server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
server/src/main/java/com/photoday/photoday/security/handler/UserAuthenticationEntryPoint.java

- 이슈 번호: #279
오리진 허용 추가, 인가 예외 처리 수정

[Fix] 오리진 허용 추가, 인가 예외 처리 수정

---

server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java
server/src/main/java/com/photoday/photoday/security/utils/CookieUtil.java

- 이슈 번호: #285 
OAuth2 주소 변경, 쿠키 도메인 수정

[Fix] OAuth2 주소 변경, 쿠키 도메인 수정 

---

client/index.html
client/src/api/User.ts
client/src/components/User/UserContentSection/UserContentSection.styles.tsx
client/src/components/User/UserContentSection/UserContentSection.tsx
client/src/components/User/UserInfoArea/UserInfoArea.tsx
client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
client/src/components/common/Pagination/Pagination.tsx

- 이슈 번호: #169 
자잘한 PR입니다 기존 코드에서 이상한 부분 수정했습니다
```tsx
export const deleteUser = async (userId: string | null) => {
const token = localStorage.getItem('accessToken');
await axios.delete<AxiosResponse>(
`${import.meta.env.VITE_APP_API}/users/${userId}`,
{
headers: {
Authorization: token,
},
},
);
```

[Feature] 기존 코드 수정

---

client/src/pages/Detail/Detail.tsx

- 이슈 번호: #153 
- 팔로우 버튼 클릭시 밑에 관련이미지들이 안나오는 버그 픽스
- 상세페이지로 최초에 들어왔을때 관련이미지들 안나오는 버그 픽스
- console.log 코드 삭제

🐛 [Fix] Detail page bug fix #153

---

client/src/api/Login.ts

[Feature] postLogin 수정

---

server/src/main/java/com/photoday/photoday/mail/developer/DeveloperEventListener.java
server/src/main/java/com/photoday/photoday/user/entity/User.java

- 이슈 번호: #
report cascade 수정
연관관계가 있을 때, 삭제 처리를 어떻게 하는 것이 가장 바람직할 것인지..

Hotfix/user report cascade 수정

---

server/src/main/resources/application.yml

:hammer: [Fix] Oauth2 redirect-uri 설정

---

client/src/api/Search.ts
client/src/components/common/ImageCardList/ImageCardList.tsx
client/src/components/common/SearchBar/SearchBar.tsx
client/src/components/common/SelectBox/SelectBox.tsx
client/src/components/common/SelectBox/SelectBoxModal.tsx
client/src/pages/Search/Search.tsx

- 이슈 번호: #181 
-  filter 기본 값 수정

[Feature] filter 기본값 수정 

---

client/src/pages/Detail/Detail.tsx
client/src/pages/Detail/DetailModal.tsx
client/src/pages/Upload/Upload.tsx

- 이슈 번호: #153 
- 태그 중복 필터링 로직 추가
- 리포트 제한 알림 추가
- 본인 게시물에 리포트 버튼 안보이게

[Feature] 태그 중복 필터링 추가, 디테일페이지 버그 수정

---

server/docker-compose.yml

[Docs] DockerFile 환경변수 추가

---

client/src/components/Upload/Tag/TagItem.tsx
client/src/pages/Detail/Detail.tsx

[Feature] 태그 클릭시 검색 페이지로 이동하는 기능 구현

---

server/src/main/java/com/photoday/photoday/image/dto/ImageDto.java
server/src/main/java/com/photoday/photoday/image/mapper/ImageMapper.java

- 이슈 번호: #308
이미지 dto 필드 수정
thumbnailUrl -> imageUrl 로 필드명 원상복구 for 프론트엔드 개발팀의 코드 수정 최소화

[Fix] image dto 필드 수정
